### ISSUE TITLE
Contructor param of ImplementationAuthority contract

### ISSUE THREAD

**Issue by aqeelVaival** [onchain-id/solidity#106]
As we need ImplementationAuthority address to deploy IdFactory contract. So a am confused here , what i should pass here inside the constructor of   ONCHAINID/Contract/Proxy/ImplementationAuthority.sol

As there is a comment available at ImplementationAuthority.sol :
// the address of implementation of ONCHAINID

but i am not getting it..not even able to grab any details from documentation or may be skipped..

**Comment by Joachim-Lebrun** [comment]
hello, implementation authority is a beacon used for proxies to find the implementation of the identity contract, therefore the address you need to use is the address of the identity implementation that you should have deployed before deploying implem authority
